name:                hotel-california
version:             0.0.1.0
github:              "parsonsmatt/hotel-california"
license:             BSD3
author:              Matt Parsons
maintainer:          parsonsmatt@gmail.com
copyright:           "2023 Matt Parsons"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/parsonsmatt/hotel-california#readme>

dependencies:
- base >= 4.7 && < 5
- hs-opentelemetry-api >= 0.0.3.6
- hs-opentelemetry-exporter-otlp
- hs-opentelemetry-propagator-w3c
- hs-opentelemetry-sdk >= 0.0.3.3
- hs-opentelemetry-utils-exceptions
- hs-opentelemetry-vendor-honeycomb
- optparse-applicative
- text
- typed-process

default-extensions:
  - DeriveGeneric
  - TypeOperators
  - OverloadedStrings
  - DataKinds
  - RecordWildCards

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded

library:
  source-dirs: src

executables:
  hotel:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hotel-california

tests:
  hotel-california-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hotel-california
